# Generated by Django 4.2.2 on 2023-07-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='user_type',
            field=models.CharField(choices=[('consumer', 'consumer'), ('supplier', 'supplier')], default='consumer', max_length=10),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
