# Generated by Django 4.2.2 on 2023-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apiuser_user_type_alter_apiuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='user_type',
            field=models.CharField(choices=[('consumer', 'consumer'), ('provider', 'provider')], default='consumer', max_length=10),
        ),
    ]
